server:
  port: 9004

spring:
  application:
    name: person-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL


hdfs:
  path: hdfs://192.168.2.2:9000
