spring:
  redis:
    # Redis服务器地址
    clusterNodes: 172.16.0.16:7001,172.16.0.16:7002,172.16.0.17:7001,172.16.0.17:7002,172.16.0.18:7001,172.16.0.18:7002
    # Redis服务器连接密码（默认为空）
    password:
    expireSeconds: 120
    # 连接超时时间（毫秒）
    commandTimeout: 10000
    # 连接池最大连接数（使用负值表示没有限制）
    maxActive: 5000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    maxWait: 3000
    # 连接池中的最大空闲连接
    maxIdle: 100
    # 连接池中的最小空闲连接
    minIdle: 5